fun assert_failed(f,err){
    let handled=false
    try{ 
        f()
    }catch e{
        handled=true
        if err!=e{
            throw "Assertion failed: \(e)==\(err)"
        }
    }
    if !handled{
        throw "Assertion failed: Expected it to throw"
    }
}

assert_failed(||{throw 'abc'},"def")
