{
  "UncaughtException": "In <Task> Error: Assertion failed: Expected it to throw\nat assert_failed (assert.np:30)\nat <main> (assert_failed4.np:3)"
}