{
  "CompileError": {
    "module": "test_invalid_try_catch3.np",
    "errors": [
      {
        "message": "Expect block after catch at end",
        "line": 3
      }
    ]
  }
}